In [ ]:
from keras.datasets import mnist
from UniversalImageRocketMnist import UniversalImageRocket
from sklearn.metrics import classification_report, confusion_matrix

# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# normalize
X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

# instantiate model
model = UniversalImageRocket(num_kernels=1000)

# training
model.fit(X_train, y_train)

# test accuracy
acc = model.score(X_test, y_test)
print(f"MNIST Test Accuracy: {acc:.4f}")

# precision, recall, f1-score & confusion matrix
y_pred = model.predict(X_test)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, digits=4))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

# Evaluation MNIST with 1000 kernels
MNIST Test Accuracy: 0.9776

Classification Report:

              precision    recall  f1-score   support

           0     0.9759    0.9918    0.9838       980
           1     0.9894    0.9885    0.9890      1135
           2     0.9777    0.9758    0.9767      1032
           3     0.9733    0.9752    0.9743      1010
           4     0.9897    0.9776    0.9836       982
           5     0.9699    0.9753    0.9726       892
           6     0.9863    0.9781    0.9822       958
           7     0.9793    0.9669    0.9731      1028
           8     0.9640    0.9887    0.9762       974
           9     0.9689    0.9574    0.9631      1009

    accuracy                         0.9776     10000
   macro avg     0.9774    0.9775    0.9775     10000
weighted avg     0.9777    0.9776    0.9776     10000


Confusion Matrix:

[[ 972    0    1    0    0    0    2    1    4    0]
 [   0 1122    5    0    2    0    4    1    0    1]
 [   2    0 1007    5    0    1    0    8    9    0]
 [   0    0    3  985    0   12    0    3    4    3]
 [   0    0    1    0  960    0    1    0    3   17]
 [   1    1    0    9    0  870    6    0    5    0]
 [   5    4    0    0    1    8  937    0    3    0]
 [   1    3   12    3    4    3    0  994    0    8]
 [   4    0    1    1    0    1    0    2  963    2]
 [  11    4    0    9    3    2    0    6    8  966]]

In [ ]:
from UniversalImageRocketCifar import UniversalImageRocket
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# initalize model
model = UniversalImageRocket(num_kernels=6000, pca_components=5000, alpha=1.0)

# load data
X_train, X_test, y_train, y_test = model.load_data()

# fit
model.fit(X_train, y_train)

# prediction
y_pred = model.predict(X_test)

# evaluation
acc = np.mean(y_pred == y_test)
print(f"\nTest Accuracy: {acc:.4f}\n")

print("Classification Report:\n", classification_report(y_test, y_pred, digits=2))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(9,7))
sns.heatmap(cm, cmap="Blues", xticklabels=range(10), yticklabels=range(10))
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("CIFAR-10 Confusion Matrix (ROCKET + RidgeClassifier)")
plt.show()


# Evaluation CIFAR-10 with 6000 kernels
Test Accuracy: 0.5003

Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.53      0.56      1000
           1       0.54      0.57      0.56      1000
           2       0.43      0.36      0.39      1000
           3       0.39      0.31      0.34      1000
           4       0.45      0.38      0.41      1000
           5       0.45      0.47      0.46      1000
           6       0.50      0.58      0.53      1000
           7       0.51      0.53      0.52      1000
           8       0.58      0.68      0.63      1000
           9       0.52      0.60      0.55      1000

    accuracy                           0.50     10000
   macro avg       0.50      0.50      0.50     10000
weighted avg       0.50      0.50      0.50     10000


 Confusion Matrix:
 [[525  38  64  25  30  25  46  40 149  58]
 [ 42 572  14  15  18  24  46  37  74 158]
 [ 81  36 357  81  97 101 119  54  49  25]
 [ 44  55  67 310  81 176 106  67  25  69]
 [ 26  44  93  57 383  76 110 123  44  44]
 [ 15  30  77 126  71 474  58  87  25  37]
 [ 25  42  68  73  65  64 580  34  16  33]
 [ 18  39  35  64  77  89  41 528  29  80]
 [ 79  64  28  23  15  16  23  17 676  59]
 [ 28 135  21  26  15  19  40  45  73 598]]

In [ ]:
import numpy as np
from UniversalImageRocket_v2 import ImageRocket2D
from sklearn.linear_model import RidgeClassifierCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from keras.datasets import mnist, cifar10
from skimage.color import rgb2gray
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

# load data
def load_mnist(n_samples=None):
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    if n_samples:
        X_train, y_train = X_train[:n_samples], y_train[:n_samples]
        X_test, y_test = X_test[:n_samples], y_test[:n_samples]
    X_train = X_train.astype("float32") / 255.0
    X_test = X_test.astype("float32") / 255.0
    return X_train, X_test, y_train, y_test

def load_cifar_gray(n_samples=None):
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()
    y_train, y_test = y_train.flatten(), y_test.flatten()
    X_train = np.array([rgb2gray(img) for img in X_train]).astype("float32")
    X_test = np.array([rgb2gray(img) for img in X_test]).astype("float32")
    if n_samples:
        X_train, y_train = X_train[:n_samples], y_train[:n_samples]
        X_test, y_test = X_test[:n_samples], y_test[:n_samples]
    return X_train/255.0, X_test/255.0, y_train, y_test

# eval function
def evaluate_dataset(X_train, X_test, y_train, y_test, dataset_name="Dataset", n_kernels=200):
    print(f"evaluating {dataset_name} with {n_kernels} kernels")
    rocket = ImageRocket2D(n_kernels=n_kernels)
    
    print("feature extraction for trainings data")
    X_train_feat = rocket.fit_transform(X_train)
    
    print("feature extraction for test data")
    X_test_feat = rocket.transform(X_test)
    
    clf = make_pipeline(StandardScaler(), RidgeClassifierCV(alphas=np.logspace(-3,3,10)))
    print("training classifier")
    clf.fit(X_train_feat, y_train)
    
    y_pred = clf.predict(X_test_feat)
    
    print(f"\n### results for {dataset_name} ###")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred))
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
    
    # visualize activation for first test image and first kernel
    example_img = X_test[0]
    example_kernel = rocket.kernels[0]
    activation = rocket._rocket_2d_activation(example_img, example_kernel)

    plt.figure(figsize=(12,4))
    plt.subplot(1,3,1)
    plt.title("original image")
    plt.imshow(example_img, cmap='gray')
    plt.subplot(1,3,2)
    plt.title("kernel")
    plt.imshow(example_kernel, cmap='bwr')
    plt.subplot(1,3,3)
    plt.title("activation matrix")
    plt.imshow(activation, cmap='hot')
    plt.show()

# mnist eval
X_train_m, X_test_m, y_train_m, y_test_m = load_mnist(n_samples=2000)
evaluate_dataset(X_train_m, X_test_m, y_train_m, y_test_m, dataset_name="MNIST", n_kernels=200)

# cifar-10 gray eval
X_train_c, X_test_c, y_train_c, y_test_c = load_cifar_gray(n_samples=2000)
evaluate_dataset(X_train_c, X_test_c, y_train_c, y_test_c, dataset_name="CIFAR-10 (Gray)", n_kernels=200)

# Results Mnist
Accuracy: 0.8885
Precision: 0.8880
Recall: 0.8869
F1-Score: 0.8866

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92       175
           1       0.95      0.99      0.97       234
           2       0.84      0.86      0.85       219
           3       0.90      0.93      0.91       207
           4       0.92      0.90      0.91       217
           5       0.93      0.88      0.90       179
           6       0.85      0.84      0.85       178
           7       0.88      0.82      0.85       205
           8       0.91      0.81      0.85       192
           9       0.83      0.88      0.85       194

    accuracy                           0.89      2000
   macro avg       0.89      0.89      0.89      2000
weighted avg       0.89      0.89      0.89      2000


Confusion Matrix:
[[168   0   1   0   0   1   2   2   1   0]
 [  0 232   0   0   0   0   1   0   0   1]
 [  1   3 188   4   4   1   3   4   7   4]
 [  1   0   6 193   0   1   0   1   0   5]
 [  0   0   0   0 195   0   7   3   0  12]
 [  1   0  10   3   0 157   3   5   0   0]
 [  8   0   3   0   6   6 150   0   5   0]
 [  0   6  12   6   5   2   0 168   1   5]
 [  9   1   1   6   1   0   9   1 155   9]
 [  4   1   3   3   2   1   1   6   2 171]]

# Results Cifar-10 Gray
Accuracy: 0.4490
Precision: 0.4370
Recall: 0.4447
F1-Score: 0.4364

Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.50      0.46       196
           1       0.52      0.61      0.56       198
           2       0.34      0.23      0.27       195
           3       0.24      0.19      0.21       199
           4       0.37      0.44      0.40       198
           5       0.40      0.28      0.33       185
           6       0.48      0.60      0.54       216
           7       0.52      0.47      0.49       193
           8       0.53      0.61      0.57       217
           9       0.53      0.53      0.53       203

    accuracy                           0.45      2000
   macro avg       0.44      0.44      0.44      2000
weighted avg       0.44      0.45      0.44      2000


Confusion Matrix:
[[ 98   9   7   2  10   4   8   8  40  10]
 [ 12 121   3   2   3   0  10   7  13  27]
 [ 26   5  45  28  29  15  23   8   9   7]
 [ 16  11  19  37  23  28  29  12   9  15]
 [  9   7  20  12  88   3  30  18   7   4]
 [  5   6  17  38  27  51  14  14   9   4]
 [  8  12   7  12  28   7 129   8   2   3]
 [  8   9   8   7  24  16  10  90   9  12]
 [ 31  11   5   8   3   3   6   5 132  13]
 [ 13  42   2   8   3   0   7   3  18 107]]
